# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatesWiki',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('candiate_name', models.CharField(max_length=255)),
                ('url_wiki', models.CharField(blank=True, max_length=255, null=True)),
                ('title_wiki', models.CharField(blank=True, max_length=255, null=True)),
                ('content_wiki', models.TextField(blank=True, null=True)),
                ('images_wiki', models.TextField(blank=True, null=True)),
                ('references_wiki', models.TextField(blank=True, null=True)),
                ('links_wiki', models.TextField(blank=True, null=True)),
                ('sections_wiki', models.TextField(blank=True, null=True)),
                ('summary_wiki', models.TextField(blank=True, null=True)),
                ('fecha_ini_det', models.DateTimeField(blank=True)),
                ('fecha_ini_f', models.DateField(blank=True)),
                ('slug', models.SlugField(max_length=15)),
            ],
            options={
                'db_table': 'candidates_wiki',
                'managed': False,
            },
        ),
    ]
