# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_politician_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='shortname',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='slug',
            field=models.SlugField(max_length=15),
        ),
    ]
