# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0003_auto_20180131_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='politcal_position_current',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
